[project]
name = "robotdetection"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "opencv-python-headless>=4.13.0.90",
    "pydantic>=2.12.5",
    "ultralytics>=8.4.4",
]
